#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* spamapi
* Easily and directly scan and block spam security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
