#import <Foundation/Foundation.h>
#import "CMSpamDetectionAdvancedRequest.h"
#import "CMSpamDetectionAdvancedResponse.h"
#import "CMSpamDetectionRequest.h"
#import "CMSpamDetectionResponse.h"
#import "CMApi.h"

/**
* spamapi
* Easily and directly scan and block spam security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMSpamDetectionApi: NSObject <CMApi>

extern NSString* kCMSpamDetectionApiErrorDomain;
extern NSInteger kCMSpamDetectionApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Perform advanced AI spam detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
/// 
///
/// @param body Spam detection request (optional)
/// 
///  code:200 message:"OK"
///
/// @return CMSpamDetectionAdvancedResponse*
-(NSURLSessionTask*) spamDetectTextStringAdvancedPostWithBody: (CMSpamDetectionAdvancedRequest*) body
    completionHandler: (void (^)(CMSpamDetectionAdvancedResponse* output, NSError* error)) handler;


/// Perform AI spam detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
/// 
///
/// @param body Spam detection request (optional)
/// 
///  code:200 message:"OK"
///
/// @return CMSpamDetectionResponse*
-(NSURLSessionTask*) spamDetectTextStringPostWithBody: (CMSpamDetectionRequest*) body
    completionHandler: (void (^)(CMSpamDetectionResponse* output, NSError* error)) handler;



@end
