#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* spamapi
* Easily and directly scan and block spam security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSpamDetectionRequest
@end

@interface CMSpamDetectionRequest : CMObject

/* Input text string to detect spam against [optional]
 */
@property(nonatomic) NSString* inputString;
/* Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. [optional]
 */
@property(nonatomic) NSString* model;

@end
