#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* spamapi
* Easily and directly scan and block spam security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSpamDetectionAdvancedResponse
@end

@interface CMSpamDetectionAdvancedResponse : CMObject

/* True if the result is not spam (clean), and false otherwise [optional]
 */
@property(nonatomic) NSNumber* cleanResult;
/* True if the input text contains spam, false otherwise [optional]
 */
@property(nonatomic) NSNumber* containsSpam;
/* True if the input text contains unsolicited sales, false otherwise [optional]
 */
@property(nonatomic) NSNumber* containsUnsolicitedSales;
/* True if the input text contains promotional content, false otherwise [optional]
 */
@property(nonatomic) NSNumber* containsPromotionalContent;
/* True if the input text contains a phishing attempt, false otherwise [optional]
 */
@property(nonatomic) NSNumber* containsPhishingAttempt;

@end
