#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* spamapi
* Easily and directly scan and block spam security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMSpamDetectionAdvancedFormField.h"
@protocol CMSpamDetectionAdvancedFormField;
@class CMSpamDetectionAdvancedFormField;



@protocol CMSpamDetectionAdvancedFormSubmissionRequest
@end

@interface CMSpamDetectionAdvancedFormSubmissionRequest : CMObject

/* Form fields and values that you received in your form submission [optional]
 */
@property(nonatomic) NSArray<CMSpamDetectionAdvancedFormField>* inputFormFields;
/* True if unsolicited sales should be allowed, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowUnsolicitedSales;
/* True if promotional content should be allowed, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowPromotionalContent;
/* True if phishing should be allowed, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowPhishing;

@end
