#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* spamapi
* Easily and directly scan and block spam security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSpamDetectionResponse
@end

@interface CMSpamDetectionResponse : CMObject

/* True if the result is not spam (clean), and false otherwise [optional]
 */
@property(nonatomic) NSNumber* cleanResult;

@end
